POST http://localhost:3000/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "GOKU",
    "password": "Las7Esferas",
    "edad": 43,
    "sexo": "masculino",
    "email": "ssjDiosUltraInstinto@example.com"
}

###
GET http://localhost:3000/api/v1/users HTTP/1.1

###
PUT http://localhost:3000/api/v1/users/68d1ff7649b946680d3cc0eb HTTP/1.1
Content-Type: application/json

{
    "email" : "SonGoku@example.com"
}